"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COMMAND_START = exports.CARD_STYLE_DRAGGABLE = exports.CARD_STYLE_LOCKET = exports.CARD_STYLE_NORMAL = exports.CLIENT_ACTION = exports.ACTION_TIMER_TICK = exports.ANIMATION_CREATURE_DISCARDED = exports.ANIMATION_MAGI_DEFEATED = exports.MESSAGE_TYPE_PROMPT_RESOLUTION = exports.MESSAGE_TYPE_CREATURE = exports.MESSAGE_TYPE_SPELL = exports.MESSAGE_TYPE_RELIC = exports.MESSAGE_TYPE_POWER = exports.MAX_COPIES_IN_DECK = exports.STEP_DRAW = exports.STEP_PRS_SECOND = exports.STEP_CREATURES = exports.STEP_ATTACK = exports.STEP_PRS_FIRST = exports.STEP_ENERGIZE = void 0;
exports.STEP_ENERGIZE = 0;
exports.STEP_PRS_FIRST = 1;
exports.STEP_ATTACK = 2;
exports.STEP_CREATURES = 3;
exports.STEP_PRS_SECOND = 4;
exports.STEP_DRAW = 5;
exports.MAX_COPIES_IN_DECK = 3;
exports.MESSAGE_TYPE_POWER = 'messages/power';
exports.MESSAGE_TYPE_RELIC = 'messages/relic';
exports.MESSAGE_TYPE_SPELL = 'messages/spell';
exports.MESSAGE_TYPE_CREATURE = 'messages/creature';
exports.MESSAGE_TYPE_PROMPT_RESOLUTION = 'messages/prompt_resolution';
exports.ANIMATION_MAGI_DEFEATED = 'magiDefeated';
exports.ANIMATION_CREATURE_DISCARDED = 'creatureDiscarded';
exports.ACTION_TIMER_TICK = 'actions/timer_tick';
exports.CLIENT_ACTION = 'clientAction';
exports.CARD_STYLE_NORMAL = 'card_style/normal';
exports.CARD_STYLE_LOCKET = 'card_style/locket';
exports.CARD_STYLE_DRAGGABLE = 'card_style/draggable';
exports.COMMAND_START = 'start';
